-- Chat app schema for project: ClientSideScripting
-- Run this in Supabase SQL Editor.

-- 1) Profiles table
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  username text not null,
  created_at timestamptz not null default now()
);

-- 2) Messages table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  constraint messages_content_not_empty check (char_length(trim(content)) > 0)
);

-- 3) Helpful indexes for chat queries
create index if not exists idx_messages_sender_receiver_created
  on public.messages (sender_id, receiver_id, created_at);

create index if not exists idx_messages_receiver_sender_created
  on public.messages (receiver_id, sender_id, created_at);

-- 4) Enable Row Level Security
alter table public.profiles enable row level security;
alter table public.messages enable row level security;

-- 5) Profiles policies
-- Any logged-in user can read profile list.
drop policy if exists "profiles_select_authenticated" on public.profiles;
create policy "profiles_select_authenticated"
  on public.profiles
  for select
  to authenticated
  using (true);

-- User can insert their own profile row.
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
  on public.profiles
  for insert
  to authenticated
  with check (auth.uid() = id);

-- User can update only their own profile row.
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles
  for update
  to authenticated
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- 6) Messages policies
-- User can read only conversations where they are sender or receiver.
drop policy if exists "messages_select_own_conversations" on public.messages;
create policy "messages_select_own_conversations"
  on public.messages
  for select
  to authenticated
  using (auth.uid() = sender_id or auth.uid() = receiver_id);

-- User can insert only messages where sender_id is themselves.
drop policy if exists "messages_insert_sender_is_auth_user" on public.messages;
create policy "messages_insert_sender_is_auth_user"
  on public.messages
  for insert
  to authenticated
  with check (auth.uid() = sender_id);

-- Optional: let users delete their own sent messages (not required by current UI)
-- drop policy if exists "messages_delete_own" on public.messages;
-- create policy "messages_delete_own"
--   on public.messages
--   for delete
--   to authenticated
--   using (auth.uid() = sender_id);

-- 7) Realtime setup
-- Ensure realtime is enabled for messages table.
alter publication supabase_realtime add table public.messages;
